### ISSUE TITLE
support  php8.1 ?

### ISSUE THREAD

**Issue by pslxx** [hsnmrtermis/milvus-php-client#1]
support  php8.1 ?

**Comment by hsnmrtermis** [comment]
Hello, it has not been tested on PHP 8.1 yet. It will be tested within 1 month, and if it doesn't work, a version compatible with 8.1 will also be released.

**Comment by pslxx** [comment]
tks, i need a milvus2.x php client on php8.1 and swoole coroutine and pool

**Comment by hsnmrtermis** [comment]
After conducting tests this month, let me share the latest status of Milvus 2 with PHP 8.1 here.

**Comment by hsnmrtermis** [comment]
Tested on php 8.2, all processes are working.
