### ISSUE TITLE
how to creates a collection？

### ISSUE THREAD

**Issue by xiejianwen** [hsnmrtermis/milvus-php-client#3]
hi, Error when I insert. how to creates a collection？

code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection: deneme2

**Comment by hsnmrtermis** [comment]
Hi, currently there is only getCollections() method for collection. php 8 tests will be done this month, I will start collections operations after the tests. I'll close the issue after I write the Collections operations.

You can create collections through the attu program until the collections are released. This week, I will add videos to the readme section about the update.

**Comment by xiejianwen** [comment]
Thank you very much, I am creating collections using attu

**Comment by hsnmrtermis** [comment]
Hello, I have updated the document. The necessary steps are shown in the document, explaining how to create a collection. Here is the part where I explain the process of creating a collection: https://hasan-mert-ermis.gitbook.io/main/milvus-2-grpc-php-client/create-collection-attu

**Comment by xiejianwen** [comment]
Thank you. This tool is very valuable. It has helped me a lot




浓浓的java咖啡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hsnmrtermis/milvus-php-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hsnmrtermis/milvus-php-client] how to creates a collection？ (Issue #3)





 
Hello, I have updated the document. The necessary steps are shown in the document, explaining how to create a collection. Here is the part where I explain the process of creating a collection: https://hasan-mert-ermis.gitbook.io/main/milvus-2-grpc-php-client/create-collection-attu
