### ISSUE TITLE
insert error

### ISSUE THREAD

**Issue by jasonhe88** [hsnmrtermis/milvus-php-client#4]
try to run the demo code, get following error when do insert:

Milvus Parameters (Result) Error: Could not resolve error, please read contents of UnaryCall.php => wait() => $event->message.

Mivus verion: 2.2

**Comment by hsnmrtermis** [comment]
Hi, in the wait method in the UnaryCall.php file at vendor/grpc/grpc/src/lib/UnaryCall.php; print_r($event->message); Can you share the output? Let's look at the error message from Milvus. It may be giving a parameter error.

[The part where you need to add the printr() function](https://www.hizliresim.com/4g5137p)

**Comment by jasonhe88** [comment]
here is the error message:

9DescribeCollection failed: can't find collection: deneme2

need to create collection "deneme2" before insert ?

**Comment by hsnmrtermis** [comment]
Yes, for now, we can only create collections through the Attu program. The document has been updated: https://hasan-mert-ermis.gitbook.io/main/milvus-2-grpc-php-client/create-collection-attu
I plan to add collection creation with PHP in the near future.
